### ISSUE TITLE
wslusc shortcut not working

### ISSUE THREAD

**Issue by marco-itnetsys** [wslutilities/wslu#110] opened 2020-04-09 16:21 UTC
**Background Information:**
 - WSL: Ubuntu 18.04
 - Version: 2.3.2-0ubuntu2~18.04.3

When creating a Win shortcut for a GUI Linux program I end up with a shortcut that is not working.

**To Reproduce**
wslusc --gui pycharm.sh

This results in a shortcut with the following target:

C:\Windows\System32\wscript.exe C:\\Users\\Marco Brieden\wslu\runHidden.vbs C:\\Users\\Marco Brieden\\AppData\\Local\\Microsoft\\WindowsApps\\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\\ubuntu1804.exe run "cd ~; . /usr/share/wslu/wsl-integration

When opened it gives this error:
"There is no file extension in "C:\Users\Marco"

**Additional context**
It looks like there are two separate issues:
1. The space in my username breaks the shortcut.
2. The max length of the "target" field has been exceeded and the command got cut off.

**Comment by patrick330602** [comment] 2020-04-10 02:41
Hi,

Thank you for the report. I noticed you are using Ubuntu version of `wslu`. Ubuntu version of WSL should report issues at <https://bugs.launchpad.net/ubuntu/+source/wslu>. All Ubuntu version issues reported will migrate to Ubuntu bug tracker. 

The issues mentioned here is also already addressed in latest 2.x version. I will link this issue on Ubuntu WSL bug report page: <https://bugs.launchpad.net/wslu/+bug/1871986>, and will report here once the issue is resolved.

**Comment by marco-itnetsys** [comment] 2020-04-13 13:47
Thanks for the quick answer!
Sorry, I didn't realize the Ubuntu version is modified. I see it in the main readme now.

Thank you for migrating the report to the correct tracker and the polite reply!

**Comment by patrick330602** [comment] 2020-04-15 09:14
FYI: the package change is merged and will be ready once 20.04 released. The process of backporting to older version will take more time.

**Closed** 2020-04-15 11:28 UTC
Labels: Bug, Status: Patched, Target: 2.x, Ubuntu Specific
